---
title: "06_Controls_part2"
author: "Carmen Coronas"
output: html_document
date: "2024-12-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r setup}
library(Matrix)
data <- read.table("/Users/carmencilla/Desktop/Master EUR/Block 2/Data Science and HR Analytics/FEM11213-Coronas/Data/abortion.dat", skip=1, sep="\t")
names(data) <- c("state","year","pop","y_viol","y_prop","y_murd",
	"a_murd","a_viol","a_prop",'prison','police',
	'ur','inc','pov','afdc','gun','beer')
data <- data[!(data$state%in%c(2,9,12)),] # AK, DC, HA are strange places
data <- data[data$year>84 & data$year<98,] # incomplete data outside these years
data$pop <- log(data$pop)
t <- data$year - 85
s <- factor(data$state) ## states are numbered alphabetically
controls <- data.frame(data[,c(3,10:17)])
## y is de-trended log crime rate, a is as described below
## note we also have violent and property crime versions
y <- data$y_murd
d <- data$a_murd
cell <- read.csv("/Users/carmencilla/Desktop/Master EUR/Block 2/Data Science and HR Analytics/FEM11213-Coronas/Data/us_cellphone.csv")
cellrate <- 5*cell[,2]/(1000*cell[,3]) # center on 1985 and scale by 1997-1985
phone <- cellrate[ t + 1 ]
t <- factor(t)
sna <- factor(s, levels=c(NA,levels(s)), exclude=NULL)
x <- sparse.model.matrix( ~ t + phone*sna + .^2, data=controls)[,-1]
```

```{r setting data for orthogonal}
library(AER)
library(gamlr)

dreg <- function(x,d){ cv.gamlr(x, d, lmr=1e-5) }
yreg <- function(x,y){ cv.gamlr(x, y, lmr=1e-5) }
```

```{r orthogonal ml}
# Orthogonal ML R Function

orthoLTE <- function(x, d, y, dreg, yreg, nfold=2)
{
	# randomly split data into folds
	nobs <- nrow(x)
    foldid <- rep.int(1:nfold, 
    	times = ceiling(nobs/nfold))[sample.int(nobs)]
    I <- split(1:nobs, foldid)
    # create residualized objects to fill
	ytil <- dtil <- rep(NA, nobs)
	# run OOS orthogonalizations
	cat("fold: ")
	for(b in 1:length(I)){
		dfit <- dreg(x[-I[[b]],], d[-I[[b]]])
		yfit <- yreg(x[-I[[b]],], y[-I[[b]]])
		dhat <- predict(dfit, x[I[[b]],], type="response")
		yhat <- predict(yfit, x[I[[b]],], type="response")
		dtil[I[[b]]] <- drop(d[I[[b]]] - dhat)
		ytil[I[[b]]] <- drop(y[I[[b]]] - yhat)
		cat(b," ")
	}
	rfit <- lm(ytil ~ dtil)
	gam <- coef(rfit)[2]
	se <- sqrt(vcovHC(rfit)[2,2])
	cat(sprintf("\ngamma (se) = %g (%g)\n", gam, se))

	return( list(gam=gam, se=se, dtil=dtil, ytil=ytil) )
}
```

```{r effects}
# OrthoML and effect of abortion access on crime

resids <- orthoLTE( x=x, d=d, y=y, 
				dreg=dreg, yreg=yreg, nfold=5) 
head(resids$dtil)
head(resids$ytil)
2*pnorm(-abs(resids$gam)/resids$se) #p-value supports no effect of abortion access on crime
```


## Example Oregon
```{r XXX}

```

## HTE. Consumer demand: beer example. 
```{r dominicks data}
load("/Users/carmencilla/Desktop/Master EUR/Block 2/Data Science and HR Analytics/FEM11213-Coronas/Data/dominicks-beer.rda")
head(wber)
```

```{r head}
wber = wber[sample(nrow(wber), 100000), ]
head(upc)
```

```{r}
dim(upc)
```

```{r uniform prices}
wber$lp <- log(12*wber$PRICE/upc[wber$UPC,"OZ"]) #ln price per 12 ounces
```

```{r elasticity}
coef( margfit <- lm(log(MOVE) ~ lp, data=wber[,]) )
```

```{r extracting words}
wber$s <- factor(wber$STORE); wber$u <- factor(wber$UPC); wber$w <- factor(wber$WEEK)
xs <- sparse.model.matrix( ~ s-1, data=wber); xu <- sparse.model.matrix( ~ u-1, data=wber); xw <- sparse.model.matrix( ~ w-1, data=wber)
# parse the item description text as a bag o' words
install.packages("tm")
library(tm)
descr <- Corpus(VectorSource(as.character(upc$DESCRIP)))
descr <- DocumentTermMatrix(descr)
descr <- sparseMatrix(i=descr$i,j=descr$j,x=as.numeric(descr$v>0), # convert from stm to Matrix format
              dims=dim(descr),dimnames=list(rownames(upc),colnames(descr)))
descr[1:5,1:6]
```

```{r controls}
controls <- cbind(xs, xu, xw, descr[wber$UPC,]) 
dim(controls)
```

```{r naive lasso}
# naive lasso
naivefit <- gamlr(x=cbind(lp=wber$lp,controls)[,], y=log(wber$MOVE), free=1, standardize=FALSE)
print( coef(naivefit)[1:2,] )
```
```{r orthoML beer}
# orthogonal ML 
resids <- orthoLTE( x=controls, d=wber$lp, y=log(wber$MOVE), dreg=dreg, yreg=yreg, nfold=5)
```


